name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 14 ]
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build-jar
        run: mvn -B install

  native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.3
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: true
      - name: build-native-image
        run: mvn -V verify -Pnative -DskipTests -DskipITs -Dpitest.skip
